### ISSUE TITLE
BuildConfig在哪里

### ISSUE THREAD

**Issue by idealgn** [iceuncle/HttpFrame#3]
com.hd123.httpframe.net.cases.base.UseCase类
` 
import com.hd123.httpframe.BuildConfig;
protected T ApiClient() {
        return NetMgr.getInstance().getRetrofit(BuildConfig.BaseUrl).create(getType());
    }`
这里的BuildConfig在哪里,

**Comment by iceuncle** [comment]
BuildConfig类是编译后生成的，在gradle中配置

**Comment by idealgn** [comment]
三克油
